### ISSUE TITLE
Only reloading main python file?

### ISSUE THREAD

**Issue by axelande** [borysiasty/plugin_reloader#14] opened 2018-02-23 15:06 UTC
I dont know if it a temporary issue with 2.99, hence the plugin reloader only reload the main python file for me, to reload other files I have to restart QGIS..

**Comment by borysiasty** [comment] 2018-02-23 18:01
I can't reproduce with master. Could you send me your plugin with a sample instruction how to reproduce (and on what system to try)?

**Comment by axelande** [comment] 2018-02-23 18:45
Very odd, I tried on some other plugins and than it worked :( (I added some random text in one of the python, that wasn't the main file, and reloaded and it couldn't load as expected.

My plugin is far from ready but it is located here: https://github.com/axelande/geodatafarm3

Is there anything in the Metadata, resources etc. that I have missed?

**Comment by borysiasty** [comment] 2018-02-23 19:55
@axelande see https://github.com/axelande/geodatafarm3/issues/1
It may be the reason, or at least I'll be able to try to reproduce it :)

**Comment by borysiasty** [comment] 2018-02-24 09:21
Closing it. The reason was wrong imports in the plugin (see the issue above).

**Closed as completed by borysiasty** 2018-02-24 09:21 UTC

**Comment by cefect** [comment] 2020-03-06 15:37
@borysiasty Thanks for the excellent plugin. I'm having the same sub-module non-loading problem.  This may also be due to the same PyQt4 issue, but the link you provided doesn't explain what the offending import statements were in the problem scripts so I'm not sure how to check. How would I find out if this is my problem?
